Neos:
  Flow:
    http:
      # Defines an explicit base URI that should be used. This affects
      # resource management, routing and all other parts accessing
      # "Http\Request->getBaseUri()".
      #
      # If this setting is NULL, the base URI will be detected from the current
      # request (default).
      baseUri: https://visualsearch.ddev.site/
